
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class beratbadan extends javax.swing.JFrame {

    String temp = "";
    Double tinggibdn, beratbdn, hasil;
    public beratbadan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jeniskelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        Cobalagi = new javax.swing.JButton();
        Tinggi = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Hasildk1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Pi = new javax.swing.JRadioButton();
        Pr = new javax.swing.JRadioButton();
        Berat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Hasilbb = new javax.swing.JTextField();
        Hasildk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 290, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 170, 30);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 50, 80, 30);

        jLabel4.setText("kg");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 250, 80, 30);

        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 130, 80, 30);

        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 170, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Berat badan ideal Anda adalah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 250, 180, 30);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(270, 210, 100, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(30, 210, 100, 30);

        Cobalagi.setText("Coba Lagi");
        Cobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobalagiActionPerformed(evt);
            }
        });
        getContentPane().add(Cobalagi);
        Cobalagi.setBounds(150, 210, 100, 30);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        getContentPane().add(Tinggi);
        Tinggi.setBounds(150, 90, 80, 30);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(150, 50, 170, 30);

        Hasildk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hasildk1ActionPerformed(evt);
            }
        });
        getContentPane().add(Hasildk1);
        Hasildk1.setBounds(20, 360, 360, 30);

        jLabel8.setText("Tinggi");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 90, 80, 30);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 90, 80, 30);

        Jeniskelamin.add(Pi);
        Pi.setText("Laki-laki");
        Pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiActionPerformed(evt);
            }
        });
        getContentPane().add(Pi);
        Pi.setBounds(280, 170, 93, 23);

        Jeniskelamin.add(Pr);
        Pr.setText("Peremuan");
        Pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrActionPerformed(evt);
            }
        });
        getContentPane().add(Pr);
        Pr.setBounds(160, 170, 100, 23);

        Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratActionPerformed(evt);
            }
        });
        getContentPane().add(Berat);
        Berat.setBounds(150, 130, 80, 30);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 130, 80, 30);

        Hasilbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilbbActionPerformed(evt);
            }
        });
        getContentPane().add(Hasilbb);
        Hasilbb.setBounds(200, 250, 80, 30);

        Hasildk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasildkActionPerformed(evt);
            }
        });
        getContentPane().add(Hasildk);
        Hasildk.setBounds(20, 320, 360, 30);

        setBounds(0, 0, 416, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
            dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
            if (Nama.getText().equals("")||Berat.getText().equals("")
              ||Tinggi.getText().equals("")) {
          JOptionPane.showMessageDialog(null, "Kotak harus diisi semua");
      } else if(Pr.isSelected()||Pi.isSelected()) {
          try {
              Proses();
          }catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Masukkan ada yang salah");
          }
      }else {
          JOptionPane.showMessageDialog(null, "Pilih jenis kelamin");
      }
        
// TODO add your handling code here:
    }//GEN-LAST:event_HitungActionPerformed

    private void CobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobalagiActionPerformed
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        Jeniskelamin.clearSelection();
        Hasilbb.setText("");
        Hasildk.setText("");
        Hasildk1.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_CobalagiActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void Hasildk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hasildk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hasildk1ActionPerformed

    private void PiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiActionPerformed
        Pi.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_PiActionPerformed

    private void PrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrActionPerformed
        Pr.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_PrActionPerformed

    private void BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratActionPerformed

    private void HasilbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilbbActionPerformed

    private void HasildkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasildkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasildkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beratbadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beratbadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JButton Cobalagi;
    private javax.swing.JTextField Hasilbb;
    private javax.swing.JTextField Hasildk;
    private javax.swing.JTextField Hasildk1;
    private javax.swing.JButton Hitung;
    private javax.swing.ButtonGroup Jeniskelamin;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton Pi;
    private javax.swing.JRadioButton Pr;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        tinggibdn = Double.parseDouble(Tinggi.getText());
        beratbdn = Double.parseDouble(Berat.getText());
        
        if(Pr.isSelected()){
            hasil = (tinggibdn - 100) * 1;
        } else if (Pi.isSelected()) {
            hasil = (tinggibdn - 104) *1;
        }
            temp = Double.toString(hasil.intValue());
            
         if(hasil < beratbdn)
         {
             Hasilbb.setText(temp);
             Hasildk.setText("Maaf "+Nama.getText()+", Sepertinya Anda Overweight");
             Hasildk1.setText("Bayaklah Olahraga dan jangan makan-makanan berkolesterol");
         }else if (hasil > beratbdn)
            {
             Hasilbb.setText(temp);
             Hasildk.setText("Maaf "+Nama.getText()+", Sepertinya Anda Underweight");
             Hasildk1.setText("Bayaklah makan-makanan berkolesterol");
            } else {
             Hasilbb.setText(temp);
             Hasildk.setText("Hallo "+Nama.getText()+", Berat badan Anda ideal");
             Hasildk1.setText("Lanjutkan pola makan yang teratur dan gaya hidup sehat");
            }
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
