
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class volume extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TPBangunRuang = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        HitungBalok = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        VolumeKubus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Jarijari = new javax.swing.JTextField();
        VolumeBola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Program Pencarian Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 310, 40);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 60, 70, 30);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(120, 100, 150, 30);
        jPanel1.add(Panjang);
        Panjang.setBounds(120, 20, 150, 30);
        jPanel1.add(Lebar);
        Lebar.setBounds(120, 60, 150, 30);

        HitungBalok.setText("Hitung");
        HitungBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungBalokActionPerformed(evt);
            }
        });
        jPanel1.add(HitungBalok);
        HitungBalok.setBounds(140, 150, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Panjang");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 20, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 100, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 20, 70, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 20, 70, 30);

        TPBangunRuang.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 20, 170, 30);
        jPanel2.add(Sisi);
        Sisi.setBounds(30, 60, 150, 30);

        VolumeKubus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolumeKubus.setText("Volume");
        VolumeKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeKubusActionPerformed(evt);
            }
        });
        jPanel2.add(VolumeKubus);
        VolumeKubus.setBounds(30, 100, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("cm");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(190, 60, 70, 30);

        TPBangunRuang.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        Jarijari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JarijariActionPerformed(evt);
            }
        });
        jPanel3.add(Jarijari);
        Jarijari.setBounds(30, 60, 150, 30);

        VolumeBola.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VolumeBola.setText("Volume");
        VolumeBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBolaActionPerformed(evt);
            }
        });
        jPanel3.add(VolumeBola);
        VolumeBola.setBounds(30, 100, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 60, 70, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 20, 200, 30);

        TPBangunRuang.addTab("Bola", jPanel3);

        getContentPane().add(TPBangunRuang);
        TPBangunRuang.setBounds(0, 50, 400, 250);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungBalokActionPerformed
        int panjang, lebar, tinggi;
        panjang =Integer.parseInt(Panjang.getText());
        lebar =Integer.parseInt(Lebar.getText());
        tinggi =Integer.parseInt(Tinggi.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch ( Exception e) {
            JOptionPane.showMessageDialog(null,"Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungBalokActionPerformed

    private void VolumeKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeKubusActionPerformed
        int sisi;
        sisi =Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch ( Exception e) {
            JOptionPane.showMessageDialog(null,"Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeKubusActionPerformed

    private void JarijariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JarijariActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_JarijariActionPerformed

    private void VolumeBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBolaActionPerformed
        float jari;
        jari =Integer.parseInt(Jarijari.getText());
        float hasil = (float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch ( Exception e) {
            JOptionPane.showMessageDialog(null,"Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HitungBalok;
    private javax.swing.JTextField Jarijari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTabbedPane TPBangunRuang;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton VolumeBola;
    private javax.swing.JButton VolumeKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
